# Generated by Django 4.0 on 2022-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_detail_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='pic',
            field=models.ImageField(height_field='100px', upload_to='', width_field='100px'),
        ),
    ]
