# Generated by Django 4.0 on 2022-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_detail_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
