# Generated by Django 4.0 on 2022-01-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='student',
        ),
    ]
